export default {
	LOAD_DECKS_REQUEST: 'LOAD_DECKS_REQUEST',
	LOAD_DECKS_SUCCESS: 'LOAD_DECKS_SUCCESS',
	LOAD_DECKS_FAILED: 'LOAD_DECKS_FAILED',
	ADD_DECK_REQUEST: 'ADD_DECK_REQUEST',
	ADD_DECK_SUCCESS: 'ADD_DECK_SUCCESS',
	ADD_DECK_FAILED: 'ADD_DECK_FAILED',
	CREATE_CARD_REQUEST: 'CREATE_CARD_REQUEST',
	CREATE_CARD_SUCCESS: 'CREATE_CARD_SUCCESS',
	CREATE_CARD_FAILED: 'CREATE_CARD_FAILED',
	REMOVE_DECK_REQUEST: 'REMOVE_DECK_REQUEST',
	REMOVE_DECK_SUCCESS: 'REMOVE_DECK_SUCCESS',
	REMOVE_DECK_FAILED: 'REMOVE_DECK_FAILED',
	REMOVE_CARD_REQUEST: 'REMOVE_CARD_REQUEST',
	REMOVE_CARD_SUCCESS: 'REMOVE_CARD_SUCCESS',
	REMOVE_CARD_FAILED: 'REMOVE_CARD_FAILED'
};